### ISSUE TITLE
rails 4 compass init trouble

### ISSUE THREAD

**Issue by idoo** [Compass/compass-rails#117]
bundle exec compass init --trace
NoMethodError on line ["223"] of /Users/ivan/.rvm/gems/ruby-2.0.0-p247/gems/compass-rails-1.1.2/lib/compass-rails.rb: undefined method `config' for nil:NilClass
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247/gems/compass-rails-1.1.2/lib/compass-rails.rb:129:in`configuration'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:44:in `configuration_for'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:22:in`add_configuration'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:107:in `add_project_configuration'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/commands/project_base.rb:31:in`add_project_configuration'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/commands/installer_command.rb:9:in `configure!'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/commands/project_base.rb:15:in`initialize'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/commands/stamp_pattern.rb:69:in `initialize'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in`new'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/bin/compass:44:in`call'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/bin/compass:23:in`load'
  /Users/ivan/.rvm/gems/ruby-2.0.0-p247@global/bin/compass:23:in `<main>'

**Comment by deivid-rodriguez** [comment]
Same error here, with `rails 4.2.6`, `ruby 2.3.0` and latest `compass-rails`. Can we reopen?
