### ISSUE TITLE
cannot load such file -- sass/script/node

### ISSUE THREAD

**Issue by cheshire137** [Compass/compass-rails#151]
When I add `gem 'compass-rails'` to my Gemfile and `bundle`, when I then try to start my server with `thin start`, I get this error:

```
/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `require': cannot load such file -- sass/script/node (LoadError)
        from /Users/me/.rvm/gems/ruby-2.0.0-p353/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'
```

**Comment by natebeaty** [comment]
For anyone else running into this, `bundle update compass` did the trick for me (on older Rails 3.2.x site with Refinery 2.1.x).

**Comment by lsag** [comment]
i had the same problem, but was my own fault. i had recently reinstalled the system, and forgot the dependencies in config.rb, namely autoprefixer-rails and sass-timestamp.

installed, it works
