### ISSUE TITLE
wrong number of arguments (2 for 1) in site.sass

### ISSUE THREAD

**Issue by deanpcmad** [Compass/compass-rails#155]
When the `compass-rails` gem is installed in my Rails 4.0.4 application I get `wrong number of arguments (2 for 1)` on all of my sass files. When removing the gem, the site works properly.

**Comment by Pjero** [comment]
I've just installed this:

gem "compass-rails", github: "Compass/compass-rails", branch: "master" 

and it works.

found it her https://github.com/Compass/compass-rails/issues/195

**Comment by nickstamas** [comment]
+1 @Pjero

**Comment by LeBenLeBen** [comment]
+1, using compass-rails on master fix the issue with Rails 4.1.8 and sass-rails 5.0.1

**Comment by craigmcnamara** [comment]
Use version 2.0.2 it has what you need.

**Comment by dbslone** [comment]
After trying to upgrade to `sass-rails 5.0.1` I started receiving the error when using `image_tag` in my erb. Didn't throw any exceptions when compiling the SASS file. 

Went through a lot of combinations from this thread but was able to fix the issue by just downgrading sass-rails to 4.0.3.

**Comment by kakipo** [comment]
I've got the same problem after `bundle update`.
I don't know what the exactly problems is, but the following combination fixed it.

```
* compass-rails (2.0.4)
* sass-rails (5.0.1)
* sprockets (2.12.3)
* sprockets-rails (2.2.4)
```

You can specify gem versions in your `Gemfile` like:

```
gem 'sass-rails', '~> 5.0'
gem 'compass-rails', '~> 2.0.4'
```

See: [Ruby's Pessimistic Operator](https://robots.thoughtbot.com/rubys-pessimistic-operator)


Hope it helps.

**Comment by macgill4444** [comment]
Thank you guys so much. I had a similar problem and @Pjero worked for me. THANK YOU!

**Comment by westonganger** [comment]
+1 @Pjero

**Comment by askuratovsky** [comment]
@kakipo thank you!
working combination of gem versions
    
    gem 'sass-rails', '~> 5.0'
    gem 'compass-rails', '~> 2.0.4'

**Comment by boriscy** [comment]
@kakipo thank you!
working combination of gem versions:

gem 'sass-rails', '~> 5.0'
gem 'compass-rails', '~> 2.0.4'
