### ISSUE TITLE
Generating sprites on Windows raises Errno::EINVAL (again)

### ISSUE THREAD

**Issue by bodrovis** [Compass/compass-rails#156]
Hello.

Firstly I faced this problem a couple of months ago when trying to upgrade one of my apps from Rails 3 to 4. I used compass there to hook up some CSS3 helpers and generate sprites. I followed the migrations guidlines, but kept getting this error:

```
Errno::EINVAL at /

Invalid argument - /nested_comments/tmp/cache/assets/development/sass/2c1508b5ee6d70f069ec044e642bbb29c0b97efe/*.pngc (in p:/rails/my/sitepoint/nested_comments/app/assets/stylesheets/application.css.scss)
```

when trying to visit the main page of the app. At that time I actually did not have a lot of time to work on this so I just gave up after some Googling (yes I saw https://github.com/chriseppstein/compass/issues/695 https://github.com/nex3/sass/issues/259 https://github.com/nex3/sass/issues/522)

Today I returned to the same app again and began migration from the very start. Guess what - I stumbled upon the very same error. I spent loads of time trying to fix it but absolutely no luck. I've tried clearing the `tmp` dir, expiring assets, changing the versions of the gems (`compass`, `compass-rails` and `sass-rails`) but really nothing helps.

I thought that this has something to do with my app and opened another very simple app that was created initially using Rails 4, no migration took place and compass was not used as well. You can clone it here: https://github.com/bodrovis/SitePointNestedComments/tree/compass_issue

I did the following:

* Added `gem 'compass-rails'` to the Gemfile
* Created an `auth` directory with a `facebook.png` image there
* Added this to the `application.css.scss`

```
@import 'auth/*.png';

.test {
  width: 32px;
  height: 32px;
  @include auth-sprite(lol);
}
```

* Added this to the `comments/index.html.erb` (the root of the app):

```
<div class="test"></div>
```

* Run `rails s`

Absolutely the same error showed up.

I really have no more ideas what can be done here. Any help will be very much appreciated.

**Comment by craigmcnamara** [comment]
Please try the latest master and reopen the ticket if the problem persists.
