### ISSUE TITLE
Rails 4.1.1 - Sass::SyntaxError - File to import not found or unreadable: compass.

### ISSUE THREAD

**Issue by andywenk** [Compass/compass-rails#164]
Hi,
we can't get compass-rails work within the following setup:

Gemfile:

```
gem 'rails', '4.1.1'

group :assets do
  gem 'sass-rails'
  gem 'compass-rails'
```

app/assets/stylesheets/application.css.scss

```
/*
 *= require_self
 */

@import "compass";
```

Stacktrace: https://friendpaste.com/3fk7mgOiStKrV27vzNSURR

The basic error message is:

```
Sass::SyntaxError - File to import not found or unreadable: compass.
```

Wether I do sth. completely wrong or I do have a misunderstanding for `@import 'compass';` in  `app/assets/stylesheets/application.css.scss`.

Any info is highly appreciated :)

Cheers

Andy

**Comment by foobarfoobar** [comment]
@bodrovis You are right. Tried many versions, but nothing worked. Any solution???

**Comment by phpcitizen** [comment]
I think it is an incompatibility with Ruby 2.x, if you go back to 1.9x should work. Developers might test with Ruby 2.2.2 to confirm.

**Comment by gon** [comment]
See https://github.com/sass/sassc-rails/issues/19#issuecomment-106140015 for a temporary fix, it worked for me.

**Comment by amitfriedman12** [comment]
Try this:

````
gem 'sass-rails'
gem 'compass-rails', github: 'Compass/compass-rails
```
You should also make sure these are NOT included inside your asset group, since it has been removed from Rails 4.0

**Comment by TheSuperFly** [comment]
I did the exact following solutions, still have the "File import not found or unreadable: compass." error.

**Comment by LindaKadz** [comment]
I had the same problem
    `sass::syntaxerror: file to import not found or unreadable: config/variables.`
, I opened a new css file (I called it custom.css) then copied all the css to the file. On application.css I removed the 

> @import "config/variables" plus all the other @imports

This worked for me, I hope it does work for you too!
