### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass-rails#175]
https://github.com/Compass/compass/issues/1657

Can you investigate?

**Comment by craigmcnamara** [comment]
There have been a bunch of new versions since this was filed so I'm closing unless it get's reopened.

**Comment by bodrovis** [comment]
Unfortunately I am getting the same error with

```
  * compass (1.0.1)
  * compass-core (1.0.1)
  * compass-import-once (1.0.5)
  * compass-rails (2.0.4)
```

**Comment by craigmcnamara** [comment]
I don't have any way of debugging windows. Do you know a way for me to get a windows environment without MS license fees?

**Comment by bodrovis** [comment]
@craigmcnamara https://www.modern.ie/en-us/virtualization-tools I believe modern.ie's VMs might help with that. They use evaluation copies of Windows.
