### ISSUE TITLE
Cannot upgrade to 2.0.0 due to mismatched sass dependency with sass-rails.

### ISSUE THREAD

**Issue by monfresh** [Compass/compass-rails#177]
Hi,

The README implies that `sass-rails` and `compass-rails` are compatible, but when I run `bundle update compass-rails` to upgrade from 1.1.7, I get the following error:

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "sass":
  In Gemfile:
    sass-rails (~> 4.0.3) ruby depends on
      sass (~> 3.2.0) ruby

    compass-rails (>= 0) ruby depends on
      sass (3.4.0)
```
Is 2.0.0 supposed to work with the current version of sass-rails in rubygems? If not, should the README be updated to let people know to point to the GitHub version of sass-rails? It looks like the sass dependency was last updated in [April](https://github.com/rails/sass-rails/commit/e56c2fbf60ef2bd879aae6f6163c90326b4017be) but a new version hasn't been released yet.

**Comment by craigmcnamara** [comment]
Try 2.0.2
