### ISSUE TITLE
compass-rails conflicting with compass

### ISSUE THREAD

**Issue by gkpo** [Compass/compass-rails#185]
I installed compass-rails with bundle install.
Now what's happening is that when I run compass watch on different projects (outside of a rails app), it freezes, until press ctrl+c , it throws this error:

Interrupt on line ["18"] of /Users/me/.rvm/gems/ruby-2.1.1/gems/compass-rails-2.0.0/lib/compass-rails.rb

I'm even wondering why compass-rails is mentioned here, as this is not inside a rails app.
The problem solves itself when I uninstall the compass-rails gem. But then I can't run my rails app anymore...

Any clue?
Thanks

**Comment by ctide** [comment]
For what it's worth, this is broken in 2.0.4.  Reverting back to 2.0.1 keeps me from having to uninstall the compass-rails gem every time I use compass in other projects.

**Comment by ctide** [comment]
Update for anyone else who comes across this issue:

Compass will break with old versions of rubygems (I had 2.0.14 installed) and compass-rails 2.0.2 or higher. Just gets into a weird loop trying to resolve dependencies. Upgrading rubygems fixed it for me, after mucking around for an hour or two trying to sort out what in compass-rails would causing the conflict.
