### ISSUE TITLE
patches/sass_importer incorrect method usage

### ISSUE THREAD

**Issue by danielpclark** [Compass/compass-rails#195]
https://github.com/Compass/compass-rails/blob/master/lib/compass-rails/patches/sass_importer.rb
- #(1) **wrong number of arguments (2 for 1)** for **line 12** in **sass_importer.rb** for **SassImporter.new**

``` ruby
paths += context.environment.paths.map { |path| self.class.parent::SassImporter.new(context, path) }
```

and **line 21**

``` ruby
:importer => self.class.parent::SassImporter.new(context, context.pathname),
```

I tracked this down.  Each library brings the class in via `SassImporter < Sass::Importers::Filesystem`.  In Sass the code reads as follows:

``` ruby
module Sass
  module Importers
    # The default importer, used for any strings found in the load path.
    # Simply loads Sass files from the filesystem using the default logic.
    class Filesystem < Base
      attr_accessor :root
      # Creates a new filesystem importer that imports files relative to a given path.
      #
      # @param root [String] The root path.
      # This importer will import files relative to this path.
      def initialize(root)
        @root = File.expand_path(root)
        @real_root = Sass::Util.realpath(@root).to_s
        @same_name_warnings = Set.new
      end
      # ...
    end
  end
end
```

Source: https://github.com/sass/sass/blob/stable/lib/sass/importers/filesystem.rb#L14

---
- #(2) **wrong number of arguments (1 for 2)** for **line 10** in **sass_importer.rb** for **SassCacheStore.new**

``` ruby
cache_store = Sprockets::SassCacheStore.new(context.environment)
```

For (2) the source method reads:

``` ruby
class CacheStore < ::Sass::CacheStores::Base
  VERSION = '1'
  def initialize(cache, version)
    @cache, @version = cache, "#{VERSION}/#{version}"
  end
  # ...
end
```

Source: https://github.com/sstephenson/sprockets/blob/2c9333bd1b6a55f791a3f2ca1389bf152cea18ba/lib/sprockets/sass_processor.rb#L260

I'm using Ruby 2.2.0.preview1, Rails 4.2.0.rc3.  And using:
gem 'compass-rails', '~> 2.0.1'
gem 'sprockets', '~> 3.0.0.beta.6'
gem 'sass-rails', '~> 5.0.0'
gem 'sass', '~> 3.4.9'

**Comment by BenjaminWilkinson** [comment]
+1 on fix, cheers.

**Comment by craigmcnamara** [comment]
Use version 2.0.2
