### ISSUE TITLE
Scss partials not reloading when compass-rails is present

### ISSUE THREAD

**Issue by Intrepidd** [Compass/compass-rails#210]
This seems related to rails/sass-rails#269
# Steps to reproduce 

- Clone the repository https://github.com/Intrepidd/compass-rails-reload-bug
- bundle install
- launch rails server and go to http://localhost:3000/home/index
- change color in test/home.scss file
- reload your page, it should NOT change
- rm -rf tmp/cache
- remove compass-rails from gemfile
- try again, this time it SHOULD work

**Comment by craigmcnamara** [comment]
@Intrepidd  So, I'm having some trouble with this it looks like we're not properly tracking asset dependencies, but I don't know where to look. I'm going to keep at it, but if you know more about Sass-rails I'd appreciate the help.

**Comment by danielpclark** [comment]
See #208

**Comment by Intrepidd** [comment]
I don't know much about the code of compass-rails and sass-rails but I'll
try to have a look

**Comment by Intrepidd** [comment]
@danielpclark , I had a quick read through the code of sass-rails and compass-rails and indeed, I think you may be onto something :)

It was probably done otherwise before, but right now, in the ``evaluate`` method of the sass template that we override, we're not setting the dependencies as it's done in sass-rails

**Comment by craigmcnamara** [comment]
Give master a try, it works in my rails 4.1 app, but I have some older ones to test and I'll be adding more testing of the compilation step on the master branch.

**Comment by jfairbank** [comment]
@craigmcnamara, I was having the same issue here. I just pulled master, and it looks like it is working for me with sass-rails 5.0.1. I edited a partial, refreshed, and the changes showed up in my stylesheet and app.

**Comment by craigmcnamara** [comment]
I just cut 2.0.2.
