### ISSUE TITLE
Sprockets/sass/compass/rails compatibility issues

### ISSUE THREAD

**Issue by jaroslawr** [Compass/compass-rails#218]
Please see: https://github.com/rails/sprockets-rails/issues/210

**Comment by craigmcnamara** [comment]
I'm aware of the issues and I'm working to get sprite support working in a way that has minimal impact on sprockets. If you have some configurations that you'd like to see tested that aren't please send a pull request so travis can ensure that you're supported. I have apps that are stuck on Rails 3.1 and more that are 4.1. My use cases are taken care of for Rails 4.2 but I'm working on fully supporting 4.2 right now.

**Comment by craigmcnamara** [comment]
https://github.com/jaroslawr/compass-sprite-issues/pull/1
