### ISSUE TITLE
Sprite caching issue

### ISSUE THREAD

**Issue by jaroslawr** [Compass/compass-rails#219]
When I open up the homepage of a completely fresh Rails 4.2 app, that just has compass-rails master version installed and a bunch of sprites defined in the scss, the page load just hangs endlessly, and I get the message:

```
Warning. Error encountered while saving cache 29b5f0cfd41b2ad2a685089c2b02a8a3326468e1/*.pngc: can't dump anonymous class #<Class:0xba765c40>
```

When there is less of those sprites in the sprite directory, the first page load is still slow, but it finally finishes after 2-3 minutes, and there is a lot more of those "can't dump anonymous class" messages being emitted. You can see the test app here:

https://github.com/jaroslawr/compass-sprite-issues

**Comment by craigmcnamara** [comment]
Have a look at the performance considerations section: http://compass-style.org/help/tutorials/spriting/

I'm working on a fix for the warning and I'll let you know when it's ready.

**Comment by craigmcnamara** [comment]
In the mean time could you try setting the sprite to generate an inline image like so? I'm going to experiment with making compass-rails sprites inline only to sidestep sprockets issues.

```scss
$numbers-inline: true;
@import "numbers/sprite-*.png";
@include all-numbers-sprites;
```

**Comment by craigmcnamara** [comment]
One problem that stands out is not using the 'oily_png' gem which speeds up `chunky_png` processing as recommended by the Compass docs for large sprite imports. There is a new build on master that fixes asset pipeline cache invalidation for sprites. As for the warning, that seems to be coming from Sass trying to cache something that might not be writable.

**Comment by jaroslawr** [comment]
* In general I am seeing this on a commercial, production app, that works just fine with compass 0.12.7, compass-rails 2.0.0, sprockets-rails 2.0.1, sprockets 2.11.0 and sass 3.2.19 and without oily_png, that's just the public test case I am able to show. 
* At this moment, I didn't check precompilation, it's about the development environment where we do not precompile assets.
* My suspicion is that something is done that is not supposed to be done at all, in tmp/ I get lots of actual files named "*.pngc" in a directory like "29b5f0cfd41b2ad2a685089c2b02a8a3326468e1" - is that intended behaviour?
* I have tried adding oily_png already and it did not help, at least not with that initial page load in the dev environment.

**Comment by jaroslawr** [comment]
@seanwalbran @craigmcnamara Thank you guys, this fixes the warning for me as well.

The first load is still very slow, though, even with oily_png. It seems afterwards everything seems fine, so maybe it's not super critical, but @craigmcnamara have you ever profiled the gem? Is there a way I could reproduce in a simple ruby script what happens on a first request to rails server when tmp/ is empty? I just would like to trigger the asset compilation in a similar way to what happens in the dev environment without precompilation, but without the actual rails server, so it's easier to wrap it in RubyProf or whatever. If you have an answer relatively off-hand, I would myself give a try profiling it, otherwise maybe it's not worth the trouble, I don't know, still doing lots of tests of our app with Rails 4.2 and all the gems updated, compass-rails among them...

Or maybe was there some general change that would explain why the first request with a cold cache is now so much longer? Maybe more things are now precompiled with the first request? As said I did not have this problem with older compass-rails versions...
