### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by KevinColemanInc** [Compass/compass-rails#224]
Any ideas whats going on here?

    $ bundle exec rake -P
    rake aborted!
    Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass/../../VERSION_NAME
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass/version.rb:37:in `read'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass/version.rb:37:in `<module:Compass>'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass/version.rb:2:in `<top (required)>'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass.rb:14:in `block in <top (required)>'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass.rb:13:in `each'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-1.0.2/lib/compass.rb:13:in `<top (required)>'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5/gems/compass-rails-1.1.6/lib/compass-rails.rb:1:in `<top (required)>'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
    /Users/kcoleman/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
    /Users/kcoleman/Sites/death/config/application.rb:7:in `<top (required)>'

**Comment by craigmcnamara** [comment]
The compass-rails 1.x.x branch isn't supported any longer. Try out 2.0.4 and let me know if it's still and issue.

**Comment by scottdavis** [comment]
compass-1.0.2 has been yanked please use compass-1.0.3
