### ISSUE TITLE
supports latest sprockets 

### ISSUE THREAD

**Issue by gaaady** [Compass/compass-rails#225]
Currently compass-rails is locked to 
gem.add_dependency 'sprockets', '< 2.13'

any idea what it takes to make it support latest sprockets?

**Comment by joallard** [comment]
+1

**Comment by craigmcnamara** [comment]
Yes, it takes analysis, software updates and testing. I'll happily take a pull request if you want to attempt an update.

**Comment by craigmcnamara** [comment]
Closing this unless someone wants to take a stab at it.
