### ISSUE TITLE
compass-rails 2.0.4 want sass-rails <= 5.0.1 

### ISSUE THREAD

**Issue by khanh** [Compass/compass-rails#229]
5.0.2. just came out, so the dependency matrix pushes me back to compass-rails 2.0.1

**Comment by PeterMozesMerl** [comment]
Same issue here.

**Comment by bragovo-test** [comment]
The same.

**Comment by badlamer** [comment]
+1

**Comment by maurosbu** [comment]
+1

**Comment by simicic** [comment]
+1

**Comment by davidochoa** [comment]
+1

**Comment by hengsokly** [comment]
+1

**Comment by cbetta** [comment]
+1

**Comment by mkluczny** [comment]
+1

**Comment by vtamara** [comment]
+1 with sass-rails 5.0.3 (published in march). https://rubygems.org/gems/sass-rails/versions/5.0.3

**Comment by pratik60** [comment]
Same here.....Is there a reason we can't update this dependency?

**Comment by pratik60** [comment]
Sorry, seems to be merged to master already...Yet not there in the latest release.

**Comment by steakchaser** [comment]
Merged into master with PR #246
