### ISSUE TITLE
can not enable sourcemaps

### ISSUE THREAD

**Issue by mixtur** [Compass/compass-rails#234]
I tried 

- `sourcemap=true` in config/compass.rb
- `config.compass.sourcemap=true` in config/environments/development.rb

Gemfile
```
ruby '2.1.3'
gem 'rails', '4.1.7'
...
gem 'sass-rails'
gem 'compass-rails'
gem 'sass-globbing'
...
```

All of the above didn't worked for me, am I doing something wrong?

**Comment by lifeiscontent** [comment]
Also would like help with this.
