### ISSUE TITLE
No application integration exists for rails

### ISSUE THREAD

**Issue by lauraannwilliams** [Compass/compass-rails#235]
I'm trying to add compass to my rails project so i can use compass watch to auto transpile my foundation files

I added compass-rails to my gem file, but when I run any compass command ( compass init, compass watch ) I get the error

"No application integration exists for rails"

I'm using Ruby 2.2.1, Rails 4.2.1 and compass-rails 2.0.1

Full bundle list:
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.1
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.1
Using globalid 0.3.5
Using activejob 4.2.1
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.1
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using ansi 1.5.0
Using awesome_print 1.6.1
Using bcrypt 3.1.10
Using coderay 1.1.0
Using better_errors 2.1.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using uniform_notifier 1.9.0
Using bullet 4.14.5
Using bundler 1.9.4
Using carrierwave 0.10.0
Using chunky_png 1.3.4
Using climate_control 0.0.3
Using cocaine 0.5.7
Using orm_adapter 0.5.0
Using ckeditor 4.1.1
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using thor 0.19.1
Using railties 4.2.1
Using coffee-rails 4.1.0
Using multi_json 1.11.0
Using sass 3.3.14
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.4
Using ffi 1.9.8
Using rb-inotify 0.9.5
Using compass 1.0.3
Using compass-rails 2.0.1 
Using responders 2.1.0
Using warden 1.2.3
Using devise 3.4.1
Using faker 1.4.3
Using font-awesome-rails 4.3.0.0
Using foundation-rails 5.5.0.0
Using friendly_id 5.1.0
Using tilt 1.4.1
Using haml 4.0.6
Using jquery-rails 3.1.2
Using jquery-ui-rails 5.0.3
Using kaminari 0.16.3
Using mini_magick 4.2.3
Using ruby-progressbar 1.7.5
Using minitest-reporters 1.0.11
Using sprockets 3.0.1
Using sprockets-rails 2.2.4
Using rails 4.2.1
Using minitest-spec-rails 5.2.0
Using nested_form 0.3.2
Using pg 0.18.1
Using rack-pjax 0.8.0
Using remotipart 1.2.1
Using safe_yaml 1.0.4
Using sass-rails 5.0.3
Using rails_admin 0.6.7
Using rdoc 4.2.0
Using redis 3.2.1
Using sdoc 0.4.1
Using simple_form 3.1.0
Using temple 0.7.5
Using slim 3.0.3
Using slim-rails 3.0.1
Using turbolinks 2.5.3
Using uglifier 2.7.1

**Comment by cmcdaniels** [comment]
Experiencing same issue with same specs -- did you happen to find a solution?

**Comment by lauraannwilliams** [comment]
No I haven't :(
