### ISSUE TITLE
Did you consider support sassc-rails?

### ISSUE THREAD

**Issue by RobWu** [Compass/compass-rails#242]
Did you consider support https://github.com/bolandrm/sassc-rails?

**Comment by bolandrm** [comment]
reference issue:  https://github.com/bolandrm/sassc-rails/issues/19

**Comment by aeberlin** [comment]
:+1:, although it looks like `sassc-rails` still doesn't have the full support `compass-rails` requires?

**Comment by craigmcnamara** [comment]
I'm not making new features for compass-rails. If you're interested, send a pull request.
