### ISSUE TITLE
Rails 4.2.1 - Sass::SyntaxError - File to import not found or unreadable: compass.

### ISSUE THREAD

**Issue by foobarfoobar** [Compass/compass-rails#244]
Hi!

#164 was closed, but I have still this issue. Tried many different versions of compass and sass and stuff, but nothing worked. Any solution??? I spent hours on that issue. Going crazy..

Thanx!!

**Comment by phpcitizen** [comment]
I think it is an incompatibility with Ruby 2.x, if you go back to 1.9x should work. Developers might test with Ruby 2.2.2 to confirm.

**Comment by phpcitizen** [comment]
In my case paperclip gem was causing File to import not found or unreadable errors...

**Comment by aripollak** [comment]
I think this the same as https://github.com/Compass/compass-rails/issues/236.

**Comment by henriquesacramento** [comment]
+1

**Comment by Mackaber** [comment]
This is very frustrating, I come up with this error, almost everytime I update, I had to find workarounds that don't use this gem

**Comment by bobmshannon** [comment]
+1

**Comment by gon** [comment]
See https://github.com/sass/sassc-rails/issues/19#issuecomment-106140015 for a temporary fix, it works.

**Comment by ACPK** [comment]
@foobarfoobar Any updates on this other than the monkey-patch?
