### ISSUE TITLE
Background-position for sprite icons is calculated wrong

### ISSUE THREAD

**Issue by RandieM** [Compass/compass-rails#245]
Hello everyone,

Since I upgraded compass and compass-rails, the background-position related to sprite icons is calculated wrong in the CSS. The result is that the wrong icon is displayed on my website every time I call for a sprite icon in my CSS.

Here are the changes to my Gemfile that caused/triggered this issue:

```
-gem 'sass-rails', '~> 4.0.5'
+gem 'sass-rails', '~> 5.0.1'
 
-gem 'compass-rails', '~> 2.0.0'
+gem 'compass-rails', '~> 2.0.4'
 
-gem 'susy', '~> 1.0.9'
+gem 'susy', '~> 2.2.5'
 
-gem 'sass', '~> 3.2.19'
+gem 'sass', '~> 3.4.16'
 
-gem 'compass', '~> 0.12.7'
+gem 'compass', '~> 1.0.3'
```

My ruby version is 2.1.2, but I have also tried upgrading to 2.2.1 and 2.2.2 and the problem is still there.
I am using Rails 4.2
I am happy to provide you with any other information that you may need.

Many thanks

PS I am not sure if I should be posting this under Compass/compass instead.

**Comment by craigmcnamara** [comment]
This is a compass bug. This project is only related to the compass/rails integration.

**Comment by RandieM** [comment]
OK, thanks. I am moving it to Compass.
