### ISSUE TITLE
Compatibility with Rails 5.0

### ISSUE THREAD

**Issue by mvastola** [Compass/compass-rails#254]
With the release of Rails 5.0.0.beta1 just days ago, many users (myself included) are seeking to upgrade their current Rails 4.2 apps to ensure forward-compatibility with this new version of Rails and to make use of its new features and capabilities.

The gemspec in the latest release of compass-rails requires a version of sprockets less than 2.13. Sprockets 2.12.x, in turn, is version-locked to rack 1.x.  Rails 5.0, however, requires at least rack with a version at or higher than 2.0, preventing any usage of this gem (or even experimentation with it) in this new version of Rails.

Fortunately, commit 68125b8570e7520d9ca8f17e11a02b83ce5f1312 (later superceded by e797d05a44e99472f123dc5b0597812e510ca892) saw this sprockets version constraint changed, which would seemingly allow compass-rails to be compatible Rails 5.0.

In light of the release of the beta of Rails 5.0, I would like to officially request that a new version of this gem be pushed to RubyGems, reflecting -- at a minimum -- the changes to the gemspec.

Thanks,
Mike

**Comment by Wolfe13** [comment]
+ 1

**Comment by Wolfe13** [comment]
+1

**Comment by craig1410** [comment]
+1

**Comment by tanelsuurhans** [comment]
+1

**Comment by mvastola** [comment]
> +1 Is there any reason for not releasing a minor version with the updated gemspec vs. waiting for a new major release for almost 6 months now?
@tanelsuurhans et al, funnily enough, I just spent an hour trying my hand at working forward from the commit marking the (current) v2.0.5 release of `compass-rails`, upgrading the `Gemspec`, and `git cherry-pick`-ing from the more recent commits to achieve Rails 5 compatibility. 

I did this, only to find out that it's only been about a dozen commits from the last release and the only major changes have been editing the `Gemspec` and fixing a few things to make Rails 5 work. Needless to say, I'd like my time back. :-)

One thing I did manage to accomplish though was to add in an `appraisal` for Rails 5, which was missing for some reason (and I fixed a warning on the Appraisal for Rails 3.1 -- no idea if that's even still supported though) and confirmed all tests are passing. I'm submitting that as a PR now (number to follow), in the hopes that evidence that the CI tests are passing will help spur a release.

**Comment by mvastola** [comment]
**UPDATE 3:** PR #258 is now *really* passing in Travis CI and is ready to merge!

**Comment by mvastola** [comment]
Closing this via #258.

**Comment by Erowlin** [comment]
We may want to add to the readme that compass-rails is compatible with Rails 5 ?
