### ISSUE TITLE
Sprite image is not created in assets:precompile

### ISSUE THREAD

**Issue by tsuwatch** [Compass/compass-rails#271]
`Errno::ENOENT: No such file or directory @ rb_sysopen - /foo/app/assets/images/icon-bar.png`

environment

```ruby
compass-rails (3.0.2)
compass (1.0.3)
sprockets (3.7.1)
sprockets-rails (3.2.0)
sass-rails (5.0.6)
```

**Comment by silva96** [comment]
having same issue

**Comment by silva96** [comment]
@tsuwatch any news on this?

**Comment by silva96** [comment]
```
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /mnt/ebs-dev/www/ibilbidea_demo/releases/20170315193852/app/assets/images/icons-s2140f783d5.png
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:99:in `binread'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:99:in `source'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/utils/gzip.rb:7:in `initialize'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:215:in `new'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:215:in `block in compile'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:135:in `block (2 levels) in find'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:80:in `find_all_linked_assets'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/mnt/ebs-dev/www/ibilbidea_demo/shared/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake stderr: Nothing written

SSHKit::Command::Failed: rake exit status: 1
```

**Comment by tsuwatch** [comment]
no... :persevere:
It seems that it is no longer being maintained

**Comment by xparta** [comment]
same issue so what do we do ? do i uninstall ?

**Comment by silva96** [comment]
we uninstalled it

Before doing it, we grabbed all the generated sprite images (the ones that
were generated in rails 4) and added them to the assets folder. Now, if we
want to add another image to the sprite, the designer will do it.

About the generated css, we opened the chrome console, inspected the
generated css for the sprite, and added it as static css in the project.

**Comment by tsuwatch** [comment]
I use `webpack-spritesmith`

**Comment by diazruy** [comment]
FYI what I found out worked for me was that I had more directories inside `app/assets/images/icons` than I was actually generating sprites for. I.e. in `application.scss` I have a number of 
```scss
@import "icons/folderx/*.png";
@import "icons/foldery/*.png";
@import "icons/folderz/*.png";
//...
@include all-folderx-sprites(...);
@include all-foldery-sprites(...);
@include all-folderz-sprites(...);
```
But given that we _also_ had `app/assets/images/icons/folderA`, deploying to heroku was failing when it at some point looked for an existing `app/assets/images/icons/folderA-XXX.png` compiled sprite, which was _not_ generated given that it wasn't explicitly included in the CSS.

After separating the "spriteable" from the "non-spriteable" icons into two separate directories (`app/assets/images/icons` and `app/assets/images/sprites`), deployment once more succeeds.

**Comment by mrjman** [comment]
I am seeing this same error when deploying to Heroku on the `assets:precompile` step, however it seems to generate the sprite locally and work fine.

For Heroku it seems that purging the repo cache fixes the deploy failure. It seems like it is tied to how assets are cached on deploys.

To use I installed the heroku-repo plugin to the Heroku CLI tools and then run `herouk repo:purge_cache --app <app_name>`
Then I can do my normal `git push` or any other method to deploy on Heroku and it works.

**Comment by xparta** [comment]
i will sure try the method above, give me two days to report weather it
works but still there is an error while using sprites.



[image: --]

Newton Robert  'Xpatter'
[image: https://]about.me/xpaterr
<https://about.me/xpaterr?promo=email_sig>

**Comment by letrungkien** [comment]
@mrjman I haven't tried your approach but do you need to purge cache in every deploy?

For me, I just commit the generated sprite images to git and do the normal git push. When there is a change in the sprite image source, compass already handled the replacement in development and I can notice that the old file is replaced then I commit the newly generated image.

Rails 5.1.5

**Comment by craigmcnamara** [comment]
This project is no longer supported.

**Comment by xparta** [comment]
but the issue is still open




[image: --]

Newton Robert  'Xpatter'
[image: https://]about.me/xpaterr
<https://about.me/xpaterr?promo=email_sig>
