### ISSUE TITLE
Issues with Rails 5.0.2

### ISSUE THREAD

**Issue by CarlJohnston** [Compass/compass-rails#273]
I'm having trouble getting `compass-rails 3.0.2` working with `rails 5.0.2`, `compass 1.0.3`,  `sass-rails 5.0.6` on `Fedora 25`.

Steps to reproduce:
1. `rails new MyProject`
2. Add `gem 'compass-rails'` to `MyProject/Gemfile.
3. `bundle install`
4. Add a `temporary.scss` file to `MyProject/app/assets/stylesheets/` and require it in `application.css` in the same path by adding `*= require temporary`
5. `bundle exec compass watch` does not observe file changes to SCSS file when modified
6. `bundle exec compass init rails . --trace` returns `No application integration exists for rails`

`bundle exec compass frameworks` returns the following:
```
  * compass
    - compass/project   - The default project layout.
    - compass/ellipsis  - Plugin for cross-browser ellipsis truncated text.
    - compass/extension - Generate a compass extension.
```

Any tips on how I can continue to debug this?

**Comment by DazDotOne** [comment]
I'm also experiencing this with Rails 5.1.4 and compass 1.0.3. Any solution would be great.

**Comment by roguemaps** [comment]
Are you by chance using gem 'quiet_assets'?

**Comment by craigmcnamara** [comment]
This integrates compass with the Rails asset pipeline and does not support any compass cli tools. Usage directions are in the README, but this project is no longer supported.
