### ISSUE TITLE
Sprites file doesn't get generated

### ISSUE THREAD

**Issue by ncri** [Compass/compass-rails#52]
I had a sprites file generated by compass-rails in assets/images. Now I wanted to regenerate that sprite as the images the sprite file is based on changed. So i deleted the file. Now compass-rails doesn't regenerate it and I get a missing image error.

This is how I create the sprites in my application.css.scss file:

```
@import "layout/*.png";
@include all-layout-sprites;
```

**Comment by uchsarath** [comment]
It works for me. Just import compass lib on the top line before any image path. Hope they gonna fix this issue.
@import 'compass' before
@import "images-path/*.png";
@include all-images-path-sprites;

** Finally, just type rake tmp:clear

**Comment by craigmcnamara** [comment]
If you're using the Compass-rails 1.x series on Rails 4 you should be using Compass-rails 2.0.x.
