### ISSUE TITLE
Sprites cache store

### ISSUE THREAD

**Issue by zemd** [Compass/compass-rails#98]
Firstly got Protocol error here http://stackoverflow.com/questions/18688887/compass-protocol-error-with-import
and founded that there were some errors on windows machines with sass, so sass filesystem cache store has function [1] that fixes cache names that contain "*"

[1] ->

```
def path_to(key)
        key = key.gsub(/[<>:\\|?*%]/) {|c| "%%%03d" % Sass::Util.ord(c)}
        File.join(cache_location, key)
end
```

but in compass-rails sass_importer you pass sprockets cache store [2], that do not know about this problem :)
[2] ->

```
     # Use custom importer that knows about Sprockets Caching
      cache_store = SassCacheStore.new(context.environment)
```

After commenting this code, compass made sprite normally. So what is this cache for? and is there should be issue for sprockets too?

Temporary solution is to change cache dir for compass, sass and assets.
But at the moment I have not succeeded to set config.cache_store and config.assets.cache_store to any value :( rails don't want to change them.

**Comment by viniciusnz** [comment]
Thanks a lot for the help guys! @wldcordeiro and @balauru, what I did was setup the assets on an external tmp dir. 

```
   mkdir /mnt/tmp
   chown railsuser:railsuser /mnt/tmp 
```
and then on `application.rb`
```
    # tmp dir for cache must be setup outside virtualbox shared folder for sass cached sprites to work
    config.assets.configure do |env|
      env.cache = ActiveSupport::Cache::FileStore.new('/mnt/tmp')
    end
```
This was quite a cryptic issue to deal with, since it seems like a VirtualBox issue, not rails related. I hope this helps people with the same issue.
